name: HEAD of dependencies

on:
  # Run daily at 1:23 UTC
  schedule:
  - cron:  '23 1 * * *'
  workflow_dispatch:

jobs:
  release-candidates:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v3

    - uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install core fonts
      if: runner.os == 'Linux'
      run: |
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get install ttf-mscorefonts-installer

    - name: Install dependencies
      run: |
        uv pip install --upgrade pip setuptools wheel
        uv pip install pytest-github-actions-annotate-failures
        uv pip --quiet install --upgrade --pre .[test]

    - name: List installed Python packages
      run: uv pip list

    - name: Test with pytest
      run: |
        pytest -r sa --mpl --mpl-results-path=pytest_results

    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: pytest_results-${{ matrix.python-version }}-${{ matrix.runs-on }}
        retention-days: 3
        path: pytest_results

  matplotlib:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v3

    - uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install core fonts
      if: runner.os == 'Linux'
      run: |
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get install ttf-mscorefonts-installer

    - name: Install dependencies
      run: |
        uv pip install --upgrade pip setuptools wheel
        uv pip install pytest-github-actions-annotate-failures
        uv pip --no-cache-dir --quiet install --upgrade .[test]
        uv pip install \
          --upgrade \
          --pre \
          --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple \
          --extra-index-url https://pypi.org/simple/ \
          matplotlib

    - name: List installed Python packages
      run: uv pip list

    - name: Test with pytest
      run: |
        pytest -r sa --mpl --mpl-results-path=pytest_results

    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: pytest_results-${{ matrix.python-version }}-${{ matrix.runs-on }}
        retention-days: 3
        path: pytest_results

  uhi:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v3

    - uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install core fonts
      run: |
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get install ttf-mscorefonts-installer

    - name: Install dependencies
      run: |
        uv pip install --upgrade pip setuptools wheel
        uv pip install pytest-github-actions-annotate-failures
        uv pip --no-cache-dir --quiet install --upgrade .[test]
        uv pip uninstall --yes uhi
        uv pip install --upgrade git+https://github.com/scikit-hep/uhi.git

    - name: List installed Python packages
      run: uv pip list

    - name: Test with pytest
      run: |
        pytest -r sa --mpl --mpl-results-path=pytest_results

    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: pytest_results-${{ matrix.python-version }}-${{ matrix.runs-on }}
        retention-days: 3
        path: pytest_results

  pytest:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v3

    - uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install core fonts
      run: |
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        sudo apt-get install ttf-mscorefonts-installer

    - name: Install dependencies
      run: |
        uv pip install --upgrade pip setuptools wheel
        uv pip install pytest-github-actions-annotate-failures
        uv pip --no-cache-dir --quiet install --upgrade .[test]
        uv pip uninstall --yes pytest
        uv pip install --upgrade git+https://github.com/pytest-dev/pytest.git

    - name: List installed Python packages
      run: uv pip list

    - name: Test with pytest
      run: |
        pytest -r sa --mpl --mpl-results-path=pytest_results

    - name: Upload pytest test results
      uses: actions/upload-artifact@v4
      if: failure()
      with:
        name: pytest_results-${{ matrix.python-version }}-${{ matrix.runs-on }}
        retention-days: 3
        path: pytest_results
